---
- name: Install Java via Homebrew
  homebrew_cask: name=caskroom/versions/java8
- name: Install Docker for Mac via Homebrew cask
  homebrew_cask: name=docker
- name: Install Python3 via Homebrew
  homebrew_cask: name=python3
- name: Install Pyenv via Homebrew
  homebrew: name=pyenv 
- name: Install AWS Cli via pip
  pip: 
    name: awscli
    state: latest
    extra_args: --upgrade --user  
- name: Install VirtualEnv via pip
  pip: 
    name: virtualenv
    state: latest
    extra_args: --upgrade --user
- name: Install pika (used by RabbitMQ)
  pip:
    name: pika
- name: Install Terraform via Homebrew
  homebrew_cask: name=terraform
- name: Install Java JDK via Homebrew
  homebrew_cask: name=java-jdk-javadoc
- name: Install Google Chrome via Homebrew
  homebrew_cask: name=google-chrome
- name: Install Git via Homebrew
  homebrew: name=git
- name: Install Node via Homebrew
  homebrew: name=node
- name: Install HerokuCli via Homebrew
  homebrew: name=heroku/brew/heroku
- name: Install Mesos via Homebrew
  homebrew: name=mesos 
- name: Install Vault via Homebrew
  homebrew: name=vault 
- name: Install VSCode via Homebrew
  homebrew_cask: name=visual-studio-code
- name: Install ZoomUS via Homebrew
  homebrew_cask: name=zoomus
- name: Install Slack via Homebrew
  homebrew_cask: name=slack
- name: Install VirtualBox via Homebrew
  homebrew_cask: name=virtualbox
- name: Install Chefdk via Homebrew
  homebrew_cask: name=chefdk